// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cw15.Infrastructure.Database;

#nullable disable

namespace cw15.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251016121320_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("cw15.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mobile"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Laptop"
                        },
                        new
                        {
                            Id = 3,
                            Name = "TV"
                        });
                });

            modelBuilder.Entity("cw15.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Samsung",
                            CategoryId = 1,
                            Color = "white",
                            Name = "A33",
                            Price = 850m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Sony",
                            CategoryId = 1,
                            Color = "Black",
                            Name = "z4",
                            Price = 400m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Samsung",
                            CategoryId = 1,
                            Color = "Black",
                            Name = "S25",
                            Price = 1200m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Samsung",
                            CategoryId = 3,
                            Color = "white",
                            Name = "acn455",
                            Price = 850m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Asus",
                            CategoryId = 2,
                            Color = "Black",
                            Name = "fx707zc",
                            Price = 1000m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Xiaomi",
                            CategoryId = 1,
                            Color = "white",
                            Name = "Poco x6",
                            Price = 900m,
                            Stock = 130
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Xiaomi",
                            CategoryId = 3,
                            Color = "white",
                            Name = "Tv3",
                            Price = 1000m,
                            Stock = 130
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Sony",
                            CategoryId = 3,
                            Color = "Black",
                            Name = "x555l",
                            Price = 900m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Xiaomi",
                            CategoryId = 1,
                            Color = "white",
                            Name = "Poco x3",
                            Price = 600m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 10,
                            Brand = "Asus",
                            CategoryId = 2,
                            Color = "Blue",
                            Name = "f15",
                            Price = 900m,
                            Stock = 80
                        });
                });

            modelBuilder.Entity("cw15.Entities.Product", b =>
                {
                    b.HasOne("cw15.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
